export {
    GDRIVE_GALLERY_API_KEY,
    GDRIVE_GALLERY_FOLDER_ID_HOME,
    GDRIVE_GALLERY_FOLDER_ID_OSS,
    GDRIVE_GALLERY_FOLDER_ID_GENERAL,
    GDRIVE_GALLERY_FOLDER_ID_GAME_DEV,
    GDRIVE_GALLERY_FOLDER_ID_DEV,
    GDRIVE_GALLERY_FOLDER_ID_DESIGN,
    GDRIVE_GALLERY_FOLDER_ID_ALGO,
    GDRIVE_GALLERY_FOLDER_ID_AI,
    GDRIVE_GALLERY_FOLDER_ID_ICPC,
  } from '$env/static/private';
  